# Unix sockets are accessible only inside this isolated container.
local all all trust
hostnossl all all 0.0.0.0/0 reject
hostnossl all all ::/0 reject
hostssl one_day one_day_app,one_day_owner 0.0.0.0/0 scram-sha-256
hostssl one_day one_day_app,one_day_owner ::/0 scram-sha-256
host all all 0.0.0.0/0 reject
host all all ::/0 reject
