listen_addresses = '*'
port = 5432
hba_file = '/etc/postgresql/pg_hba.conf'
ssl = on
ssl_cert_file = '/etc/postgresql/tls/server.crt'
ssl_key_file = '/etc/postgresql/tls/server.key'
ssl_min_protocol_version = 'TLSv1.2'
password_encryption = 'scram-sha-256'
max_connections = 40
shared_buffers = '64MB'
work_mem = '4MB'
maintenance_work_mem = '32MB'
statement_timeout = '8s'
idle_in_transaction_session_timeout = '15s'
log_min_error_statement = panic
log_statement = none
timezone = 'UTC'
