import type { Diary } from "./types";
// Fictional examples for the design prototype. Never insert these into production.
export const demoDiaries: Diary[] = [
  {
    id: "demo-dali-1",
    placeId: "dali",
    nickname: "一只慢慢走的水獭",
    date: "2026-10-02",
    body: "早上去市场买了两个饵块。沿着湖边走，走到一个没什么人的地方就坐下了。\n\n也没做什么特别的事。看一个小朋友反复把石头扔进水里，看云一点点挪到山后面。\n\n傍晚骑车回来，裤脚全是灰。今天没有完成任何计划，但回家的路上觉得，这一天挺好的。",
    cost: 47.5,
    currency: "CNY",
    score: 86,
    isDemo: true,
    comments: [
      {
        id: "dc1",
        nickname: "暂时不赶路",
        body: "这种什么都没做，却觉得一天很完整的感觉。",
      },
      {
        id: "dc2",
        nickname: "一只慢慢走的水獭",
        body: "对。平时总觉得得干点什么，今天没有。",
      },
    ],
  },
  {
    id: "demo-dali-2",
    placeId: "dali",
    nickname: "不想起床的土豆",
    date: "2026-10-01",
    body: "换了个地方住，醒来还是先刷手机。点了一份外卖，下午下雨，一直没出门。\n\n原来到了想去的地方，也不会自动变成一个会生活的人。晚上出门买水，店主家的猫在门口睡觉，蹲着看了一会儿。",
    cost: 168,
    currency: "CNY",
    score: 51,
    isDemo: true,
    comments: [],
  },
  {
    id: "demo-xihu",
    placeId: "xihu",
    nickname: "口袋里有两颗栗子",
    date: "2026-10-02",
    body: "睡醒快十一点了。煮面的时候打碎了一个碗，收拾完索性把厨房也擦了一遍。\n\n下午沿着湖边走了很远，买了一小袋糖炒栗子。回家看了半部电影，另一半留给明天。",
    cost: 38,
    currency: "CNY",
    score: 74,
    isDemo: true,
    comments: [],
  },
  {
    id: "demo-xuanwu",
    placeId: "xuanwu",
    nickname: "今天走了很多路",
    date: "2026-10-02",
    body: "在家躺了半天，还是决定出门。带了水，没有想好去哪儿，最后走到了玄武湖。\n\n路上听完一张很久没听的专辑。天黑得比想象中快，回来吃了碗鸭血粉丝汤。",
    cost: 29,
    currency: "CNY",
    score: 78,
    isDemo: true,
    comments: [],
  },
  {
    id: "demo-yangshuo",
    placeId: "yangshuo",
    nickname: "一阵晚到的风",
    date: "2026-10-01",
    body: "租了辆自行车，路上一直能看到山。午后下雨，躲进一家小店吃米粉。\n\n雨下了四十分钟，店主跟隔壁的人聊了四十分钟。我坐在旁边听，不太听得懂，也不着急。",
    cost: 92,
    currency: "CNY",
    score: 89,
    isDemo: true,
    comments: [],
  },
  {
    id: "demo-kamakura",
    placeId: "kamakura",
    nickname: "海边的第七块石头",
    date: "2026-10-02",
    body: "坐电车去了海边。在便利店买了饭团，坐在台阶上慢慢吃完。\n\n风很大，书翻了好几次页，最后也没读多少。回程的车厢很安静，窗外一直是蓝色的。",
    cost: 1850,
    currency: "JPY",
    score: 91,
    isDemo: true,
    comments: [],
  },
  {
    id: "demo-kyoto",
    placeId: "kyoto",
    nickname: "把伞忘在昨天",
    date: "2026-10-02",
    body: "原本想去的店没开。沿着旁边的小路走，找到一家只有几个座位的咖啡店。\n\n下午写了两页东西，剩下的时间在看窗外。店里的人来来去去，我的那杯咖啡已经凉了。",
    cost: 2400,
    currency: "JPY",
    score: 82,
    isDemo: true,
    comments: [],
  },
  {
    id: "demo-shibuya",
    placeId: "shibuya",
    nickname: "末班车上的蘑菇",
    date: "2026-10-01",
    body: "出门见了一个很久没见的朋友。吃饭、逛书店，聊了许多不太重要的事。\n\n回家后累得不想说话。城市很热闹，有时候热闹也会让人有点孤独。",
    cost: 6200,
    currency: "JPY",
    score: 63,
    isDemo: true,
    comments: [],
  },
  {
    id: "demo-paris",
    placeId: "paris",
    nickname: "面包掉了三粒屑",
    date: "2026-10-01",
    body: "上午洗衣服，下午去图书馆。买了面包和奶酪，在公园找了一张空椅子。\n\n旁边有人下棋，我看了很久，虽然没看懂谁赢了。天凉下来的时候才想起回家。",
    cost: 14.8,
    currency: "EUR",
    score: 80,
    isDemo: true,
    comments: [],
  },
  {
    id: "demo-sf",
    placeId: "san-francisco",
    nickname: "还剩一点电",
    date: "2026-10-01",
    body: "早上有雾，走到街角买咖啡。下午和朋友在公园待了一会儿，太阳出来后，草地上慢慢坐满了人。\n\n晚上做了两人份的意面，一个人吃了。明天就不用做饭了。",
    cost: 32,
    currency: "USD",
    score: 76,
    isDemo: true,
    comments: [],
  },
];
export const money = (amount: number, currency: string) =>
  new Intl.NumberFormat("zh-CN", {
    style: "currency",
    currency,
    maximumFractionDigits: amount % 1 === 0 ? 0 : 2,
  }).format(amount);
